server:
  port: 9292
spring:
  datasource:
    url: jdbc:h2:mem:mydb
  driverClassName: org.h2.Driver
  username: sa
  password:
  jpa:
  console:
    enabled: true
    path: /h2-console
  settings:
    trace: false
    web-allow-others: true